receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: "7745187966:AAG36PddfZsomfIwDaE_p3ltUgwhgJt9JJo"
    chat_id: -932781628
    send_resolved: true

route:
  receiver: 'telegram'
  routes:    
  - receiver: 'telegram'
    group_wait: 10s
    matchers:
    - severity=~"warning|critical|firing"

#  https://api.telegram.org/botINSERT_BOT_ID_HERE/getUpdates - to get chat_id
#  amtool --alertmanager.url=http://localhost:9093/ alert add alertname="Test alert" severity="warning" job="test-job" - to send test alert
